version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: clazico-postgres
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-clazico}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-clazico_secret}
      POSTGRES_DB: ${POSTGRES_DB:-clazico_store}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-clazico} -d ${POSTGRES_DB:-clazico_store}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - clazico-network

  redis:
    image: redis:7-alpine
    container_name: clazico-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - clazico-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  clazico-network:
    driver: bridge
